services:
    php:
        build:
            context: .
            dockerfile: .docker/dev/Dockerfile
            args:
                USER_ID: ${USER_ID:-1000}
                USER_NAME: ${USER_NAME:-jesper}
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www/html
        ports:
            - '8080:8080'
            - '5173:5173'
